<?PHP
  $bauplan->includeCss('../css/static.css');

  $contact = $mgdb->get('body')->load('templates/about/contact.bau');
  $contact->get('contact-table-row-usda')->loop(array(

    array('Image'  => '/images/person/maizegdb/Dark/small/andorf.jpg',
          'Name'  => 'Carson Andorf',
          'Role'  => 'Computational Biologist',
          'Expertise' => 'Genomics, AI/machine learning, bioinformatics, tool development',
          'Email' => 'carson.andorf@usda.gov',
          'FindPerson' => '<a href="/person?id=1204262"><img src="/icon/person_16.png"></a>',
         ),
    array('Image'  => '/images/person/maizegdb/Dark/small/cannon.jpg',
          'Name'  => 'Ethy Cannon',
          'Role'  => 'Computational Biologist and Bioinformaticist',
          'Expertise' => 'Genomic data, integrated gene model data, pan-genomics, tool development',
          'Email' => 'ethy.cannon@usda.gov',
    'Email-opts' => '?cc=ekcannon@iastate.edu',
          'FindPerson' => '<a href="/person?id=1079092"><img src="/icon/person_16.png"></a>',
          ),
    array('Image'  => '/images/person/maizegdb/Dark/small/portwood.jpg',
          'Name'  => 'John Portwood',
          'Role'  => 'IT-Specialist',
          'Expertise' => 'Website/Database/Systems Administration, tool development',
          'Email' => 'john.portwood@usda.gov',
          'FindPerson' => '<a href="/person?id=2772801"><img src="/icon/person_16.png"></a>',
        ),
    array('Image'  => '/images/person/maizegdb/Dark/small/woodhouse.jpg',
          'Name'  => 'Margaret Woodhouse',
          'Role'  => 'Computational Biologist, sequence curator',
          'Expertise' => 'Bioinformatics, genome curation, comparative genomics, and pan-genomics',
          'Email' => 'margaret.woodhouse@usda.gov',
          'FindPerson' => '<a href="/person?id=595845"><img src="/icon/person_16.png"></a>',
         ),

   ));

   $contact->get('contact-table-row-nonfed')->loop(array(
    array('Image'  => '/images/person/maizegdb/Dark/small/gardiner.jpg',
          'Name'  => 'Jack Gardiner',
          'Role'  => 'Curator',
          'Expertise' => 'Microarrays, RNA-Seq, gene expression, physical and genetic mapping, epigenetics, podcasts',
          'Email' => 'gardinerj@missouri.edu',
          'FindPerson' => '<a href="/person?id=12890"><img src="/icon/person_16.png"></a>',
          ),
    array('Image'  => '/images/person/maizegdb/StephenHarding.jpg',
          'Name'  => 'Stephen Harding',
          'Role'  => 'Post-doctoral Fellow',
          'Expertise' => 'Molecular Biology, Bioinformatics, and Biostatistics',
          'Email' => 'stephen.harding84@gmail.com',
          'FindPerson' => '<a href="/person?id=10043227"><img src="/icon/person_16.png"></a>',
          ),
    array('Image'  => '/images/person/maizegdb/OliviaHaley.jpg',
          'Name'  => 'Olivia Haley',
          'Role'  => 'Post-doctoral Fellow',
          'Expertise' => 'Machine learning; protein function; food safety; protein-protein interaction',
          'Email' => 'ochaley@ksu.edu',
          'FindPerson' => '<a href="/person?id=10040859"><img src="/icon/person_16.png"></a>',
         ),
    array('Image'  => '/images/person/maizegdb/RitaHayford.jpg',
          'Name'  => 'Rita Hayford',
          'Role'  => 'Post-doctoral Fellow',
          'Expertise' => 'Bioinformatics, Genomics, Gene and Genome Curation',
          'Email' => 'Rita.Hayford@usda.gov',
          'FindPerson' => '<a href="/person?id=10000118"><img src="/icon/person_16.png"></a>',
         ),
    array('Image'  => '/images/person/maizegdb/LauraTibbs-Cortes.jpg',
          'Name'  => 'Laura Tibbs-Cortes',
          'Role'  => 'Post-doctoral Fellow',
          'Expertise' => 'Genomics, Bioinformatics, GWAS.',
          'Email' => 'laura.tibbs-cortes@usda.gov',
          'FindPerson' => '<a href="/person?id=3218447"><img src="/icon/person_16.png"></a>',
         ),
  ));

   $contact->get('contact-table-row-student')->loop(array(
   array('Image'  => '/images/person/maizegdb/silloutte.jpg',
          'Name'  => 'Shatabdi Sen',
          'Role'  => 'Graduate Student',
          'Expertise' => 'Genetics, genomics, computational biology',
          'Email' => 'shatabdi@iastate.edu',
          'FindPerson' => '',
          )
  ));

   $contact->get('contact-table-row-alumni')->loop(array(
    array('Image'  => '/images/person/maizegdb/silloutte.jpg',
          'Name'  => 'Sagnik Banerjee',
          'Role'  => 'Former Graduate Student',
          'Expertise' => 'Genome assembly and annotation, RNA-Seq',
          'Email' => '',
          'FindPerson' => '',
          ),
   array('Image'  => '/images/person/maizegdb/Dark/small/campbell.jpg',
          'Name'  => 'Darwin Campbell',
          'Role'  => 'Former IT-Specialist',
          'Expertise' => 'Systems Administration, IT management, logistics coordinator',
          'Email' => 'darwin@iastate.edu',
          'FindPerson' => '<a href="/person?id=882336"><img src="/icon/person_16.png"></a>',
          ),
   array('Image'  => '/images/person/maizegdb/Dark/small/Cho_KT.jpg',
          'Name'  => 'Kyoung Cho',
          'Role'  => 'Former Graduate Student',
          'Expertise' => 'Interface development, machine learning',
          'Email' => '',
          'FindPerson' => '',
          ),
    array('Image'  => '/images/person/maizegdb/Dark/small/harper.jpg',
          'Name'  => 'Lisa Harper',
          'Role'  => 'Curator & Outreach Coordinator Emeritus',
          'Expertise' => 'Plant development, phenotypes, meiosis, cell biology, cytogenetics, outreach',
          'Email' => 'lisaharper@me.com',
          'FindPerson' => '<a href="/person?id=16267"><img src="/icon/person_16.png"></a>',
         ),
    array('Image'  => '/images/person/maizegdb/silloutte.jpg',
          'Name'  => 'Carolyn Lawrence-Dill',
          'Role'  => 'Former Lead Scientist',
          'Expertise' => 'Bioinformatics, plant biology, computer science',
          'Email' => 'triffid@iastate.edu',
          'FindPerson' => '<a href="/person?id=146822"><img src="/icon/person_16.png"></a>',
          ),
   array('Image'  => '/images/person/maizegdb/silloutte.jpg',
          'Name'  => 'Nancy Manchanda',
          'Role'  => 'Former Graduate Student',
          'Expertise' => 'B104 Genome, genome assembly and annotation',
          'Email' => '',
          'FindPerson' => '',
          ),
    array('Image'  => '/images/person/maizegdb/Dark/small/schaeffer.jpg',
          'Name'  => 'Mary Schaeffer',
          'Role'  => 'Curator Emeritus',
          'Expertise' => 'Functional annotation and ontologies;  phenotypic variations; metabolic networks; genetic and physical maps.',
          'Email' => 'schaefferm@missouri.edu ',
          'FindPerson' => '<a href="/person?id=16635"><img src="/icon/person_16.png"></a>',
         ),
    array('Image'  => '/images/person/maizegdb/Dark/small/sen.jpg',
          'Name'  => 'Taner Sen',
          'Role'  => 'Computational Biologist',
          'Expertise' => 'Genomics, metabolic pathways, bioinformatics.',
          'Email' => 'taner.sen@usda.gov',
          'FindPerson' => '<a href="/person?id=1080055"><img src="/icon/person_16.png"></a>',
         ),
  ));
/*
  $contact->get('key-list1')->loop(array(
      array('KeyCollaborator'  => 'Hank Bass', 'KeyPerson' => '/person?id=15943'),
      array('KeyCollaborator'  => 'Ed Buckler', 'KeyPerson' => '/person?id=103840'),
      array('KeyCollaborator'  => 'Natalia de Leon', 'KeyPerson' => '/person?id=172645'),
      array('KeyCollaborator'  => 'Christine Elsik', 'KeyPerson' => '/person?id=304576'),
      array('KeyCollaborator'  => 'Candice Gardner', 'KeyPerson' => '/person?id=16212'),
      array('KeyCollaborator'  => 'Matthew Hufford', 'KeyPerson' => '/person?id=1280599'),
      array('KeyCollaborator'  => 'Shawn Kaeppler', 'KeyPerson' => '/person?id=16353'),
      array('KeyCollaborator'  => 'Carolyn Lawrence-Dill', 'KeyPerson' => '/person?id=146822'),
      array('KeyCollaborator'  => 'Eric Lyons', 'KeyPerson' => '/person?id=975676'),
      array('KeyCollaborator'  => 'Sue Rhee', 'KeyPerson' => '/person?id=103986'),
      array('KeyCollaborator'  => 'Marty Sachs', 'KeyPerson' => '/person?id=13016'),
      array('KeyCollaborator'  => 'Pat Schnable', 'KeyPerson' => '/person?id=13023'),
      array('KeyCollaborator'  => 'James Schnable', 'KeyPerson' => '/person?id=981154'),
      array('KeyCollaborator'  => 'Taner Sen', 'KeyPerson' => '/person?id=1080055'),
      array('KeyCollaborator'  => 'Erik Vollbrecht', 'KeyPerson' => '/person?id=16898'),
      array('KeyCollaborator'  => 'Justin Walley', 'KeyPerson' => '/person?id=2714509'),
      array('KeyCollaborator'  => 'Ramona Walls', 'KeyPerson' => '/person?id=2772717'),
      array('KeyCollaborator'  => 'Kan Wang', 'KeyPerson' => '/person?id=102922'),
      array('KeyCollaborator'  => 'Doreen Ware', 'KeyPerson' => '/person?id=514952'),
  ));
*/

  $contact->get('contact-info1')->loop(array(
      array('WorkingGroupMembers'  => 'Alice Barkan', 'WorkingPerson' => '/person?id=15938'),
      array('WorkingGroupMembers'  => 'Qunfeng Dong', 'WorkingPerson' => '/person?id=641933'),
      array('WorkingGroupMembers'  => 'Candice Hirsch', 'WorkingPerson' => '/person?id=974437'),
      array('WorkingGroupMembers'  => 'David Jackson', 'WorkingPerson' => '/person?id=40249'),
      array('WorkingGroupMembers'  => 'Thomas Lubberstedt', 'WorkingPerson' => '/person?id=100157'),
      array('WorkingGroupMembers'  => 'Dorrie Main (Chair)', 'WorkingPerson' => '/person?id=751978'),
      array('WorkingGroupMembers'  => 'Marty Sachs*', 'WorkingPerson' => '/person?id=13016'),
      array('WorkingGroupMembers'  => 'James Schnable', 'WorkingPerson' => '/person?id=981154'),
      array('WorkingGroupMembers'  => 'Mark Settles', 'WorkingPerson' => '/person?id=104045'),

  ));


  $contact->get('contact-info2')->loop(array(
      array('AdditionalInfo'  => '* These close collaborators serve in an ex officio capacity on the Working Group.'),
  ));
?>
