<?PHP
/* file: mnl.php
 *
 * purpose: display information about the Maize Newsletter
 *
 * IMPORTANT NOTE: HTML should not be in the .php files!
 *                 However, this is too much HTML to quickly shift to 
 *                 mnl-content.bau.
 *
 *                 (Dear reader, if you have the time, feel free to fix this!)
 */
 
$mnl = $mgdb->get('body')->load('templates/community/mnl.bau');
$mnl->get('mnl-volume')->loop(array(
            array('Volume' => '<a href="https://mnl.maizegdb.org/94">Volume 94 (2020)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/93">Volume 93 (2019)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/92">Volume 92 (2018)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/91">Volume 91 (2017)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/90">Volume 90 (2016)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/89">Volume 89 (2015)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/88">Volume 88 (2014)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/87">Volume 87 (2013)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/86">Volume 86 (2012)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/85">Volume 85 (2011)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/84">Volume 84 (2010)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/83/">Volume 83 (2009)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/82/">Volume 82 (2008)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/81/">Volume 81 (2007)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/80/">Volume 80 (2006)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/79/">Volume 79 (2005)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/78/">Volume 78 (2004)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/77/">Volume 77 (2003)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/76/">Volume 76 (2002)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/75/">Volume 75 (2001)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/74/">Volume 74 (2000)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/73/">Volume 73 (1999)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/72/">Volume 72 (1998)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/71/">Volume 71 (1997)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/70/">Volume 70 (1996)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/69/">Volume 69 (1995)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/68/">Volume 68 (1994)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/67/">Volume 67 (1993)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/66/">Volume 66 (1992)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/65/">Volume 65 (1991)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/64/">Volume 64 (1990)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/63/">Volume 63 (1989)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/62/">Volume 62 (1988)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/61/">Volume 61 (1987)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/60/">Volume 60 (1986)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/59/">Volume 59 (1985)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/58/">Volume 58 (1984)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/57/">Volume 57 (1983)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/56/">Volume 56 (1982)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/55/">Volume 55 (1981)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/54/">Volume 54 (1980)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/53/">Volume 53 (1979)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/52/">Volume 52 (1978)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/51/">Volume 51 (1977)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/50/">Volume 50 (1976)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/49/">Volume 49 (1975)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/48/">Volume 48 (1974)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/47/">Volume 47 (1973)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/46/">Volume 46 (1972)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/45/">Volume 45 (1971)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/44/">Volume 44 (1970)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/43/">Volume 43 (1969)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/42/">Volume 42 (1968)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/41/">Volume 41 (1967)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/40/">Volume 40 (1966)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/39/">Volume 39 (1965)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/38/">Volume 38 (1964)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/37/">Volume 37 (1963)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/36/">Volume 36 (1962)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/35/">Volume 35 (1961)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/34/">Volume 34 (1960)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/33/">Volume 33 (1959)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/32">Volume 32 (1958)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/31">Volume 31 (1957)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/30">Volume 30 (1956)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/29">Volume 29 (1955)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/28">Volume 28 (1954)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/27">Volume 27 (1953)</a><br>'),
            array('Volume' => '<a href="https://mnl.maizegdb.org/26">Volume 26 (1952)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/25/">Volume 25 (1951)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/24/">Volume 24 (1950)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/23/">Volume 23 (1949)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/22/">Volume 22 (1948)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/21/">Volume 21 (1947)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/20/">Volume 20 (1946)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/19/">Volume 19 (1945)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/18/">Volume 18 (1944)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/17/">Volume 17 (1943)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/16/">Volume 16 (1942)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/15/">Volume 15 (1941)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/14/">Volume 14 (1940)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/13/">Volume 13 (1939)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/12/">Volume 12 (1938)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/11/">Volume 11 (1937)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/10/">Volume 10 (1936)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/09/">Volume 09 (1935)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/08/">Volume 08 (1934, Nov)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/07/">Volume 07 (1934, Sep)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/06/">Volume 06 (1934, Feb)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/05/">Volume 05 (1934, Jan)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/04/">Volume 04 (1933, Nov)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/03/">Volume 03 (1933, Jan)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/02/">Volume 02 (1932, Oct)</a><br>'),
			array('Volume' => '<a href="https://mnl.maizegdb.org/mnl/01/">Volume 01 (1929, Apr)</a><br>')
			));
			
?>
